config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	post 'create_user', to: 'events#create_user'
	get 'event_token/:token', to: 'events#event_token', as: 'event_token'
	get 'create_user/:id/new', to: 'events#new_user', as: 'new_user'
	resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/token.rb
class Token < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	extend Enumerize
	enumerize :status_id, in: {ok: 1, ng: 2, unknown: 0}, default: :ok
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
		session[:event] = @event
		@user = User.new
		@event_user = User.where(event_id: params[:id])
		@token = Token.find_by(event_id: @event.id)
	end

	def new
		@event = Event.new
		@token = Token.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			@token = Token.new
			@token.token = SecureRandom.hex
			@token.event_id = @event.id
			@token.save
			redirect_to event_path(@event), notice: 'create event'
		end
	end

	def event_token
		@token = Token.find_by(token: params[:token])
		if @token != nil
			@event = Event.find_by(id: @token.event_id)
			redirect_to new_user_path(@event)
			session[:event] = @event
		end
	end

	def new_user
		@user = User.new
		@event = session[:event]
	end

	def create_user
		@user = User.new(user_params)
		if @user.save
			@event_h = session[:event]
			@event = Event.find_by(id: @event_h['id'])
			@user.update(:event_id => @event.id)
			redirect_to event_path(@event)
		end
	end

	private
	def event_params
		params.require(:event).permit(:event_name, :event_at)
	end

	def user_params
		params.require(:user).permit(:name, :comment, :status_id, :event_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
	end

	private
	def user_params
		params.require(:user).permit(:name, :comment, :status_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/event_user.html.erb
<% form_for(@user) do |f| %>
	<%= f.text_field :name %>
<% end %>

app/views/events/index.html.erb
<h1>index</h1>
<% @events.each do |event| %>
	<%= event.event_name %>
	<%= event.event_at %>
	<br>
<% end %>

app/views/events/new.html.erb
<h1>
イベント作成
</h1>
<%= form_for(@event) do |f| %>
	イベント名
	<%= f.text_field :event_name %>

	イベント日時
	<%= f.datetime_select :event_at %>

	<%= f.submit "作成", class: "btn btn-large btn-primary" %>	
<% end %>

app/views/events/new_user.html.erb
<%= @event['event_name'] %>

<%= form_for(@user, :url => {:controller => :events, :action => :create_user}) do |f| %>
        <%= f.text_field :name %>
        <%= f.text_area :comment %>
        <%= f.select :status_id, User.status_id.options %>
        <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.event_name %></h1>
<%= @event.event_at %><br>
<%= event_token_url(@token.token) %><br>
<div>
	<% @event_user.each do |user| %>
		名前:
		<%= user.name %>
		ステータス:
		<%= user.status_id %>
		コメント:
		<%= user.comment %>
		<br>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>